server:
  port: 8083

spring:
  application:
    name: platform-service
  datasource:
    url: jdbc:h2:file:./data/myappdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
      path: /h2-console
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# 禁用启动时检查Eureka server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true 