server:
  port: 8082

spring:
  application:
    name: driver-service
  websocket:
    allowed-origins: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    com.lvchiyang.Driver: DEBUG 